package ExceptionHandling;
class ArithmeticTest{
	public static void divison(int n1,int n2) {
		try {
			int result=n1/n2;
			System.out.println("Division:"+result);
		}
		catch(Exception ex) {
			System.out.println("Exception occured");
			System.out.println("Exception:"+ex.getMessage());
			
		}
		System.out.println("remainign code here");
	}
}

public class ExceptionHandlingExamp1 {
public static void main(String[] args) {
	ArithmeticTest.divison(100, 0);
	ArithmeticTest.divison(0, 100);
	ArithmeticTest.divison(200,300);
	
	
	
}
}
