/*package ExceptionHandling;
class ArithmeticTest{
	public static void divison(int n1,int n2) {
		int result=0;
		//try {
			result=n1/n2;
		//}
		//catch(Exception ex) {
			System.out.println("Exception occured");
			System.out.println("Exception:"+ex.getMessage());
			
		}finally {
			System.out.println("Division:"+result);
		}
		System.out.println("remainign code here");
	}
}

public class ExceptionHandlingExamp1 {
public static void main(String[] args) {
	ArithmeticTest.divison(100, 0);
	ArithmeticTest.divison(0, 100);
	ArithmeticTest.divison(200,5);
	
	
	
}
}*/
